### ISSUE TITLE
The calculation method of 5 times run

### ISSUE THREAD

**Issue by fredy0108** [xmed-lab/CSS-SemiVideo#3]
dear authors,

i am quite interested about your work, and i want to know the way calculate std.
i noticed that in file 'vidsegin_teachstd_kd.py/video_segin.py', the eval is calucated for 5 times, is the reported std calculated between the 5 tests; or more like 5times run*5 tests?
Does the 5 times run use the same split file?

thanks

**Comment by ackbar03** [comment]
Hi, 

Thanks for the interest!

For the model input, the 20 frames are sampled at a fixed FPS. For the most accurate inference, the prediction of a video should be the average prediction of all possible sampled inputs. This is very time consuming however. 

The eval you are referring to, which is calculated 5 times in the code, randomly samples frames in the entire video 5 times only to perform inference. This is slightly less accurate than full evaluation but still accurate enough for the model to be evaluated. 

Switching between full evaluation (using every possible sampled frame) and evaluation from 5 samples can be controlled by the --full_test/--quick_test option. 


This is unrelated from how standard deviation is calculated however. The std. values are calculated by running the entire training process 5 times and finding the standard deviation of the evaluation results, which unfortunately was quite computationally intensive. The same split file is used. 

Hope this answers your question!

**Comment by fredy0108** [comment]
Got it and quitely understood the difficulty about computing cost. 
Thanks for your reply and wish you have a nice day.
